---
overwrite: false
prefer_grub_d: false
keep_distributor: false
kernel_params:
  - "rhgb"
  - "quiet"
defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: 0
    GRUB_DISABLE_SUBMENU: true
    GRUB_DISABLE_RECOVERY: true
    GRUB_BACKGROUND: "/usr/share/vendetta/grub-bg.png"
    GRUB_ENABLE_BLSCFG: true
always_use_defaults: true
