# Vendetta Council OS — ext4 (default) or btrfs, both offered on erase.
---
efi:
    mountPoint:      "/boot/efi"
    recommendedSize: 512MiB
    minimumSize:     300MiB
    label:           "EFI"
userSwapChoices:
    - none
    - small
    - suspend
    - file
drawNestedPartitions:   false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType:  "ext4"
availableFileSystemTypes:  ["ext4","btrfs"]
showNotEncryptedBootMessage: false
luksGeneration: luks2
partitionLayout:
    - name: "vendetta"
      filesystem: "unknown"
      mountPoint: "/"
      size: 100%
