# Fedora live: the running root is an overlay on the base ext4 rootfs.img, which
# dracut's dmsquash-live exposes as /dev/mapper/live-base. Copy that.
---
unpack:
    - source: "/dev/mapper/live-base"
      sourcefs: "ext4"
      destination: ""
