#!/bin/sh
set -e
u=$(awk -F: '$3>=1000 && $3<65000 {print $1; exit}' /etc/passwd)
[ -n "$u" ] || exit 0

users=/var/lib/AccountsService/users
icons=/var/lib/AccountsService/icons

[ -f "$users/$u" ] && grep -q '^Icon=' "$users/$u" && exit 0

install -d "$icons" "$users"
install -m 0644 /usr/share/vendetta/sigil.png "$icons/$u"

if [ -f "$users/$u" ]; then
	if grep -q '^\[User\]' "$users/$u"; then
		sed -i "/^\[User\]/a Icon=$icons/$u" "$users/$u"
	else
		printf '\n[User]\nIcon=%s\n' "$icons/$u" >> "$users/$u"
	fi
else
	cat > "$users/$u" <<INNER
[User]
Icon=$icons/$u
SystemAccount=false
INNER
fi
