---
kernelSearchPath: "/usr/lib/modules"
kernelPattern: "^vmlinuz.*"
efiBootLoader: "grub"
efiBootloaderId: "vendetta"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
