---
gsName: vendettaBootloader
overwrite: false
prefer_grub_d: false
keep_distributor: false
kernel_params:
  - "nowatchdog"
defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: 0
    GRUB_DISABLE_SUBMENU: false
    GRUB_DISABLE_RECOVERY: true
    GRUB_BACKGROUND: "/usr/share/vendetta/grub-bg.png"
always_use_defaults: true
