# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0

efi:
    mountPoint:         "/boot"
    recommendedSize:    1GiB
    minimumSize:        32MiB
    label:              "EFI"

userSwapChoices:
    - none
    - small
    - suspend

luksGeneration: luks2

drawNestedPartitions:   false

alwaysShowPartitionLabels: true

showNotEncryptedBootMessage:   false

initialPartitioningChoice: none
initialSwapChoice: none

defaultFileSystemType:  "ext4"

availableFileSystemTypes:  ["btrfs","ext4"]

partitionLayout:
    - filesystem: "ext4"
      noEncrypt: false
      mountPoint: "/"
      size: 100%
