# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
modules-search: [ local, /run/current-system/sw/lib/calamares/modules ]

instances:
- id:       unfree
  module:   packagechooserq
  config:   unfree.conf
- id:       login
  module:   packagechooser
  config:   packagechooser-login.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - users
  - packagechooser
  - packagechooser@login
  - partition
  - summary
- exec:
  - partition
  - mount
  - nixos
  - users
  - umount
- show:
  - finished

branding: nixos

prompt-install: false

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
