[terminal]
vt = 1

[default_session]
command = "tuigreet --time --remember --asterisks --greeting 'VENDETTA COUNCIL OS  —  Ideas are bulletproof' --theme 'border=cyan;text=white;prompt=cyan;time=cyan;action=cyan;button=cyan;container=black;input=white'"
user = "greeter"
