[Greeter]
background=/usr/share/wallpapers/Vendetta/contents/images/1920x1080.png
background-color=#04090A
theme-name=Breeze-Dark
icon-theme-name=Papirus-Dark
font-name=Chakra Petch 10
draw-user-backgrounds=false
draw-grid=false
